# Lab system allocation tool

There are list of students who need to either practice programming or need to give a test and you need allocate lab systems in your college to these students. 

Below is the list of students and their roll numbers, 
Student_list = {'Raja':701,'Teja':702,'Suraj':770...}
Name - Raja , Roll Number - 701

List of Labs and their system allocation status is as given below

{'MCA Lab':{'1':['Free','Good'],'2':['Allocated','Repair'],'3':['Free','Good'] ....}, 'Cisco Lab':{'1':['Free','Good'],'2':['Allocated','Repair'],'3':['Free','Good'] ....}}

Main dictonary - Lab Name : dicitonary of System ID's
Second Dictionary(values) - System ID : [Allocation status , Repair status]

Allocate the system to students in order of the ID's and Labs as below

Raja - 701 - MCA Lab - 1
Teja - 701 - MCA Lab - 3
Suraj - 770 - Cisco Lab - 1


## Solution

As per the problem description we see that there are 3 students with 3 unique roll no's
Hence:
<li> We would first create two seperate lists of roll numbers and name and merge them into a dictionary.
<li> Post the creating the first dictionary we would then create the second dictionary corresponding to the Labs and there status.

In [2]:
#Name of students:
names=['Raja','Teja','Suraj']

#Roll no list:
roll=[701,702,770]

#Creating a dictionary combining the above two lists:

stu_data = dict(zip(names,roll))

print(stu_data)


{'Raja': 701, 'Teja': 702, 'Suraj': 770}


In [3]:
#Creating a lab dictionary:
Lab_dict={'MCA Lab':{'1': ['Free', 'Good'], '2': ['Allocated', 'Repair'], '3': ['Free', 'Good']},'Cisco Lab':{'1': ['Free', 'Good'], '2': ['Allocated', 'Repair'], '3': ['Free', 'Good']}}
print(Lab_dict)

{'MCA Lab': {'1': ['Free', 'Good'], '2': ['Allocated', 'Repair'], '3': ['Free', 'Good']}, 'Cisco Lab': {'1': ['Free', 'Good'], '2': ['Allocated', 'Repair'], '3': ['Free', 'Good']}}


###### As per the problem allocation
Raja - 701 - MCA Lab - 1 Teja - 701 - MCA Lab - 3 Suraj - 770 - Cisco Lab - 1

In [4]:
#Assigning the values of the list names as per the allocation
Raja=Lab_dict['MCA Lab']['1']
Teja=Lab_dict['MCA Lab']['3']
Suraj=Lab_dict['Cisco Lab']['1']

#printing final output
print('Raja would be alloted MCA Lab 1 which is',Raja)
print('Teja would be alloted MCA Lab 2 which is',Teja)
print('Suraj would be alloted Cisco Lab 1 which is',Suraj)

Raja would be alloted MCA Lab 1 which is ['Free', 'Good']
Teja would be alloted MCA Lab 2 which is ['Free', 'Good']
Suraj would be alloted Cisco Lab 1 which is ['Free', 'Good']
